# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://lrita.github.io
date_format: "ordinal"
title: 源代码
subtitle: ""
description: "lrita's blog"
keywords: 源代码, golang, c, cpp, c++, rust
favicon: /favicon.ico
timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 4

# ---------------- #
#      Author      #
# ---------------- #
author: Neal Hu
organization: Weibo, Inc.
organization_url: http://www.weibo.com
github_username: lrita
location: Beijing, China
email: lrita@163.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /categories/
    label: 分类

  -
    href: /wiki/
    label: 维基

  -
    href: /links/
    label: 链接

  -
    href: /about/
    label: 关于

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/

repository: lrita/lrita.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, duoshuo
comments_provider: disqus
disqus_username:

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: xxxxxxx

# ---------------- #
#      Datas       #
# ---------------- #
skill_software_keywords: [C, C++, Python, Go, Rust]
skill_research: [分布式, 存储, 消息队列]
